server:
  port: ":8080"
  python_env_path: ""

database:
  driver: "mysql"
  host: "localhost"
  port: "3306"
  user: "db_username"
  password: "db_user_password"
  name: "database_name"

# JWT Secret Key
auth:
  secretKey: "your-secret-key"